import {FormEvent, useEffect, useMemo, useState, type CSSProperties} from "react";
import {
  Activity, ArrowRight, BarChart3, Bell, BookOpen, Check, ChevronDown, ChevronRight,
  CircleAlert, CircleCheck, Clock3, Command, Copy, Download, FileChartColumn, FileSearch,
  Eye, EyeOff, FileText, Fingerprint, Gauge, LayoutDashboard, LibraryBig, LockKeyhole, LogOut, Menu,
  MessageSquareText, MoreHorizontal, PieChart, Plus, Search, ShieldCheck, Sparkles,
  Target, Trash2, TrendingUp, Upload, X, Zap
} from "lucide-react";
import {api, auth, type AuditEvent, type Citation, type Document, type Result, type User} from "./api";
import {supabase} from "./supabase";

type Tab = "overview" | "studio" | "documents" | "audit";
type Mode = "portfolio_summary" | "risk_insight" | "client_communication" | "question";

const previewMode = import.meta.env.VITE_PREVIEW_MODE === "true";
const previewUser: User = {id: "preview", name: "Junaid Abdulhamid", email: "junaid@example.com", role: "Analyst"};
const previewDocuments: Document[] = [
  {id: "1", filename: "Q2 Portfolio Review.pdf", content_type: "application/pdf", status: "ready", page_count: 84, error: null, metadata_: {portfolio: "Balanced Growth"}, created_at: "2026-08-29T15:00:00Z"},
  {id: "2", filename: "Investment Policy Statement.pdf", content_type: "application/pdf", status: "ready", page_count: 26, error: null, metadata_: {portfolio: "Balanced Growth"}, created_at: "2026-08-27T15:00:00Z"},
  {id: "3", filename: "Global Markets Outlook.pdf", content_type: "application/pdf", status: "ready", page_count: 48, error: null, metadata_: {portfolio: "Research"}, created_at: "2026-08-25T15:00:00Z"},
  {id: "4", filename: "Alternatives Exposure.csv", content_type: "text/csv", status: "processing", page_count: 12, error: null, metadata_: {portfolio: "Alternatives"}, created_at: "2026-08-30T12:00:00Z"},
  {id: "5", filename: "Fixed Income Attribution.pdf", content_type: "application/pdf", status: "ready", page_count: 31, error: null, metadata_: {portfolio: "Core Fixed Income"}, created_at: "2026-08-21T15:00:00Z"}
];
const previewResult: Result = {
  id: "preview-result", model: "FinSight grounded synthesis", answer: "The portfolio remains positioned for balanced growth, with public equities representing the primary return engine while high-quality fixed income provides meaningful downside ballast. [S1]\n\nThe most material near-term risk is concentration within U.S. large-cap technology. The Q2 review indicates that the five largest positions account for 28% of public equity exposure, creating sensitivity to a narrow set of earnings outcomes. [S1] Liquidity remains sound: 81% of assets can be converted to cash within five business days under normal market conditions. [S2]\n\nConsider reviewing the technology allocation against the policy range and confirming that the alternatives pacing plan remains aligned with projected capital calls. This is an evidence-based observation, not investment advice.",
  citations: [
    {document_id: "1", filename: "Q2 Portfolio Review.pdf", chunk_id: "c1", page_number: 18, excerpt: "U.S. large-cap equities contributed 62% of quarterly portfolio appreciation. The five largest public equity positions represent 28% of total public equity exposure, led by technology and communication services holdings.", relevance: .94},
    {document_id: "2", filename: "Investment Policy Statement.pdf", chunk_id: "c2", page_number: 9, excerpt: "The portfolio shall maintain sufficient liquid assets to meet twelve months of projected distributions. At least 75% of total assets should remain convertible to cash within five business days under normal market conditions.", relevance: .89},
    {document_id: "3", filename: "Global Markets Outlook.pdf", chunk_id: "c3", page_number: 32, excerpt: "Market breadth remains a key consideration as index-level returns continue to be driven by a small cohort of large-cap growth companies.", relevance: .83}
  ]
};
const previewAudit: AuditEvent[] = [
  {id: "a1", action: "generation.created", resource_type: "generation", resource_id: "8ac3f921", detail: {mode: "risk_insight", source_count: 3}, created_at: "2026-08-30T14:42:00Z"},
  {id: "a2", action: "document.uploaded", resource_type: "document", resource_id: "21df47a0", detail: {filename: "Alternatives Exposure.csv"}, created_at: "2026-08-30T12:00:00Z"},
  {id: "a3", action: "user.login", resource_type: "user", resource_id: "preview", detail: {}, created_at: "2026-08-30T11:48:00Z"},
  {id: "a4", action: "generation.created", resource_type: "generation", resource_id: "4be039bf", detail: {mode: "portfolio_summary", source_count: 4}, created_at: "2026-08-29T17:16:00Z"}
];
const modes: {id: Mode; label: string; short: string; icon: typeof PieChart; prompt: string}[] = [
  {id: "portfolio_summary", label: "Portfolio brief", short: "Positioning, performance and allocation", icon: PieChart, prompt: "Summarize the portfolio's positioning, key performance drivers, and allocation changes for the investment committee."},
  {id: "risk_insight", label: "Risk assessment", short: "Concentration, liquidity and exposure", icon: Gauge, prompt: "Identify the most material portfolio risks, rank them by significance, and cite the supporting evidence."},
  {id: "client_communication", label: "Client update", short: "Clear, polished communication", icon: MessageSquareText, prompt: "Draft a concise client update covering portfolio developments, outlook, and the actions under review."},
  {id: "question", label: "Research query", short: "Interrogate the source library", icon: FileSearch, prompt: "What are the strongest evidence-backed conclusions across the selected source material?"}
];

function Logo() { return <div className="brand"><span className="brand-symbol"><BarChart3 /></span><span>FinSight</span></div>; }

function Auth() {
  const [registering, setRegistering] = useState(false); const [busy, setBusy] = useState(false); const [guestBusy, setGuestBusy] = useState(false); const [showPassword, setShowPassword] = useState(false); const [error, setError] = useState(""); const [confirmationEmail, setConfirmationEmail] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const data = new FormData(event.currentTarget); const email = String(data.get("email")); try { if (registering) { const result = await auth.signUp(String(data.get("name")), email, String(data.get("password"))); if (result.needsConfirmation) { setConfirmationEmail(email); return; } } else await auth.signIn(email, String(data.get("password"))); } catch (e) { const message = e instanceof Error ? e.message : "Unable to continue"; setError(message.includes("Invalid login") ? "Email or password is incorrect." : message.includes("Email not confirmed") ? "Confirm your email before signing in. Check your inbox for the verification link." : message); } finally { setBusy(false); } }
  async function enterAsGuest() { setGuestBusy(true); setError(""); try { await auth.signInAsGuest(); } catch (e) { const message = e instanceof Error ? e.message : "Guest access is temporarily unavailable."; setError(message.includes("Anonymous sign-ins are disabled") ? "Guest access is not enabled for this workspace." : message); } finally { setGuestBusy(false); } }
  return <main className="nocturne-auth"><div className="nocturne-glow" aria-hidden="true"/><div className="nocturne-stripes" aria-hidden="true"/><div className="nocturne-wrap">
    <header className="nocturne-nav"><Logo/><div className="nocturne-nav-meta"><span>Secure access</span><span className="nocturne-folio">FS·01 / 2026</span><span className="nocturne-status"><i/>Authentication services operational</span></div></header>
    <div className="nocturne-grid"><aside className="nocturne-features" aria-label="FinSight trust principles"><p>Investment research<br/>infrastructure</p>{[["01","Private retrieval","Your source library remains isolated."],["02","Traceable synthesis","Claims resolve to page-level evidence."],["03","Auditable history","Material actions retain provenance."]].map(([number,title,copy]) => <article key={number}><span>{number}</span><div><strong>{title}</strong><small>{copy}</small></div></article>)}</aside>
      <section className="nocturne-content"><div className="nocturne-hero"><h1>Evidence,<br/><em>made actionable.</em></h1><p>Build investment conclusions that withstand scrutiny. Every answer stays tethered to the source material behind it.</p></div>
        <div className="nocturne-access"><section className="nocturne-card" aria-label={confirmationEmail ? "Email confirmation required" : registering ? "Create an account" : "Sign in"}><div className="nocturne-card-bar"/><header><div><span>Identity ledger / {confirmationEmail ? "Pending" : registering ? "New" : "Member"}</span><h2>{confirmationEmail ? "Verify your identity." : registering ? "Open a workspace." : "Enter FinSight."}</h2></div><ShieldCheck/></header>
          {confirmationEmail ? <div className="nocturne-confirmation"><span className="nocturne-confirmation-mark"><ShieldCheck/></span><p className="confirmation-kicker">Confirmation required</p><h3>Check your inbox</h3><p>A secure activation link was sent to <strong>{confirmationEmail}</strong>. Open it in this browser, then return here to sign in.</p><ol><li><i/>Email dispatched</li><li><i/>Confirm identity</li><li><i/>Enter workspace</li></ol><button className="nocturne-primary" onClick={() => {setConfirmationEmail(""); setRegistering(false);}}>Return to member access<ArrowRight/></button><small>Delivery can take a minute. Check your spam folder before requesting another account.</small></div> : <><div className="nocturne-tabs" role="tablist" aria-label="Authentication mode"><button type="button" role="tab" aria-selected={!registering} className={!registering ? "active" : ""} onClick={() => {setRegistering(false); setError("");}}>Member access</button><button type="button" role="tab" aria-selected={registering} className={registering ? "active" : ""} onClick={() => {setRegistering(true); setError("");}}>Create account</button></div>
            <form key={registering ? "register" : "login"} className="nocturne-form" onSubmit={submit}>{registering && <label><span>Full name<small>Your workspace display name</small></span><input name="name" required minLength={2} autoComplete="name" placeholder="Alex Morgan" autoFocus/></label>}<label><span>Work email<small>Identifies your workspace</small></span><input name="email" type="email" required autoComplete="email" inputMode="email" placeholder="alex@firm.com" autoFocus={!registering}/></label><label><span>Password<small>{registering ? "12 characters minimum" : "Your secure credential"}</small></span><div className="nocturne-password"><input name="password" type={showPassword ? "text" : "password"} required minLength={12} autoComplete={registering ? "new-password" : "current-password"} placeholder={registering ? "Create a secure password" : "Enter your password"}/><button type="button" onClick={() => setShowPassword(value => !value)} aria-label={showPassword ? "Hide password" : "Show password"} aria-pressed={showPassword}>{showPassword ? <EyeOff/> : <Eye/>}</button></div></label>{registering && <p className="nocturne-password-guide"><span>12+ characters</span><span>Use a unique passphrase</span></p>}{error && <div className="nocturne-error" role="alert"><CircleAlert/><span><strong>Access could not be completed</strong>{error}</span></div>}<button className="nocturne-primary" disabled={busy || guestBusy}>{busy ? <><Activity className="spin"/>Verifying identity</> : <>{registering ? "Create secure workspace" : "Continue to workspace"}<ArrowRight/></>}</button></form>
            {!registering && <footer className="nocturne-guest"><div><span>Temporary access / 24h</span><h3>Explore without an account</h3><p>Opens an isolated guest workspace. Data cannot be recovered after sign-out.</p></div><button type="button" onClick={() => void enterAsGuest()} disabled={busy || guestBusy}>{guestBusy ? <><Activity className="spin"/>Opening</> : <>Guest mode<ArrowRight/></>}</button></footer>}</>}
        </section><aside className="nocturne-trust"><blockquote><span>FS / Note 01</span>“A conclusion is only as strong as the evidence trail that supports it.”<cite>FinSight research principle</cite></blockquote><div><p><LockKeyhole/>Encrypted at rest and in transit</p><p><ShieldCheck/>Protected by Supabase Auth</p></div></aside></div>
      </section></div></div>
  </main>;
}

export default function App() {
  const [user, setUser] = useState<User | null>(previewMode ? previewUser : null); const [loading, setLoading] = useState(!previewMode);
  useEffect(() => { if (previewMode) return; let active = true; const resolveProfile = () => api.me().then(profile => {if (active) setUser(profile);}).catch(() => {if (active) setUser(null);}).finally(() => {if (active) setLoading(false);}); void supabase.auth.getSession().then(({data}) => data.session ? resolveProfile() : setLoading(false)); const {data: listener} = supabase.auth.onAuthStateChange((event, nextSession) => { if (event === "SIGNED_OUT" || !nextSession) {setUser(null); setLoading(false);} else if (event === "SIGNED_IN") {setLoading(true); queueMicrotask(() => void resolveProfile());} else if (event === "USER_UPDATED") queueMicrotask(() => void resolveProfile()); }); return () => {active = false; listener.subscription.unsubscribe();}; }, []);
  if (loading) return <LoadingScreen />;
  if (!user) return <Auth />;
  return <Workspace user={user} onLogout={() => {void auth.signOut().finally(() => setUser(null));}} />;
}

function LoadingScreen() { return <div className="loading-screen"><Logo/><div className="loading-line"><span/></div><p>Preparing your research workspace</p></div>; }

function Workspace({user, onLogout}: {user: User; onLogout: () => void}) {
  const [documents, setDocuments] = useState<Document[]>(previewMode ? previewDocuments : []); const [selected, setSelected] = useState<string[]>([]); const [mode, setMode] = useState<Mode>("portfolio_summary"); const [query, setQuery] = useState(""); const [result, setResult] = useState<Result | null>(null); const [audit, setAudit] = useState<AuditEvent[]>(previewMode ? previewAudit : []); const [tab, setTab] = useState<Tab>("overview"); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [mobile, setMobile] = useState(false);
  const load = () => previewMode ? Promise.resolve() : api.documents().then(setDocuments).catch(e => setError(e.message));
  useEffect(() => { void load(); }, []); useEffect(() => { if (previewMode || !documents.some(d => d.status === "processing")) return; const timer = window.setInterval(load, 2500); return () => clearInterval(timer); }, [documents]);
  async function upload(file?: File) { if (!file) return; setBusy(true); setError(""); try { if (previewMode) { const demo: Document = {id: crypto.randomUUID(), filename: file.name, content_type: file.type || "text/plain", status: "processing", page_count: null, error: null, metadata_: {}, created_at: new Date().toISOString()}; setDocuments(current => [demo, ...current]); } else { await api.upload(file, ""); await load(); } setTab("documents"); } catch (e) { setError(e instanceof Error ? e.message : "Upload failed"); } finally {setBusy(false);} }
  async function generate() { if (!query.trim()) return; setBusy(true); setError(""); try { if (previewMode) { await new Promise(resolve => window.setTimeout(resolve, 900)); setResult(previewResult); } else setResult(await api.generate(query, mode, selected)); } catch (e) {setError(e instanceof Error ? e.message : "Generation failed");} finally {setBusy(false);} }
  async function openAudit() { setTab("audit"); if (!previewMode) setAudit(await api.audit()); }
  const navigate = (next: Tab) => {setTab(next); setMobile(false);};
  const isGuest = user.email.endsWith("@anonymous.finsight.local");
  return <div className="app-shell">
    <aside className={`side-nav ${mobile ? "open" : ""}`}><div className="nav-brand"><Logo/><button onClick={() => setMobile(false)} aria-label="Close menu"><X/></button></div><div className={`workspace-switcher ${isGuest ? "guest-workspace" : ""}`}><div className="workspace-monogram">{isGuest ? "G" : "BG"}</div><div><small>{isGuest ? "Temporary session" : "Portfolio workspace"}</small><strong>{isGuest ? "Guest research" : "Balanced Growth"}</strong></div>{isGuest ? <Clock3/> : <ChevronDown/>}</div><p className="nav-section">Workspace</p><nav><NavButton icon={LayoutDashboard} label="Overview" active={tab === "overview"} onClick={() => navigate("overview")}/><NavButton icon={Sparkles} label="Analysis desk" active={tab === "studio"} onClick={() => navigate("studio")} badge="⌘ K"/><NavButton icon={LibraryBig} label="Source library" active={tab === "documents"} onClick={() => navigate("documents")} count={documents.length}/></nav><p className="nav-section nav-section-secondary">Controls</p><nav><NavButton icon={ShieldCheck} label="Audit activity" active={tab === "audit"} onClick={() => void openAudit()}/></nav><div className="nav-status"><span><i/> Systems operational</span><small>{isGuest ? "Temporary guest data" : "Retrieval index current"}</small></div><div className="profile"><div className="avatar">{initials(user.name)}</div><div><strong>{user.name}</strong><span>{isGuest ? "Temporary guest" : user.role}</span></div><button onClick={onLogout} aria-label="Sign out"><LogOut/></button></div></aside>
    {mobile && <button className="nav-scrim" onClick={() => setMobile(false)} aria-label="Close navigation"/>}
    <main className="app-main"><Topbar tab={tab} busy={busy} openMenu={() => setMobile(true)} upload={upload}/>{error && <div className="global-error" role="alert"><CircleAlert/><span>{error}</span><button onClick={() => setError("")}><X/></button></div>}{tab === "overview" && <Overview user={user} documents={documents} navigate={navigate}/>} {tab === "studio" && <Studio documents={documents} selected={selected} setSelected={setSelected} mode={mode} setMode={setMode} query={query} setQuery={setQuery} generate={generate} busy={busy} result={result}/>} {tab === "documents" && <Documents documents={documents} upload={upload} remove={async id => {if (!previewMode) await api.removeDocument(id); setDocuments(current => current.filter(item => item.id !== id));}}/>} {tab === "audit" && <Audit events={audit}/>}</main>
  </div>;
}

function NavButton({icon: Icon, label, active, onClick, count, badge}: {icon: typeof Activity; label: string; active: boolean; onClick: () => void; count?: number; badge?: string}) { return <button className={active ? "active" : ""} onClick={onClick}><Icon/><span>{label}</span>{count !== undefined && <b>{count}</b>}{badge && <kbd>{badge}</kbd>}</button>; }
function initials(name: string) { return name.split(" ").map(part => part[0]).join("").slice(0, 2).toUpperCase(); }

function Topbar({tab, busy, openMenu, upload}: {tab: Tab; busy: boolean; openMenu: () => void; upload: (file?: File) => void}) {
  const meta = {overview: ["Workspace", "Overview"], studio: ["Research", "Analysis desk"], documents: ["Knowledge base", "Source library"], audit: ["Governance", "Audit activity"]}[tab];
  return <header className="topbar"><button className="menu-button" onClick={openMenu} aria-label="Open navigation"><Menu/></button><div className="breadcrumbs"><span>{meta[0]}</span><ChevronRight/><strong>{meta[1]}</strong></div><div className="top-actions"><button className="search-button"><Search/><span>Search workspace</span><kbd>⌘ K</kbd></button><button className="icon-button" aria-label="Notifications"><Bell/><i/></button><label className="button button-dark upload-control"><Plus/>{busy ? "Working…" : "Add source"}<input type="file" accept=".pdf,.txt,.md,.csv" hidden disabled={busy} onChange={e => upload(e.target.files?.[0])}/></label></div></header>;
}

function Overview({user, documents, navigate}: {user: User; documents: Document[]; navigate: (tab: Tab) => void}) {
  const ready = documents.filter(d => d.status === "ready"); const pages = documents.reduce((sum, d) => sum + (d.page_count || 0), 0); const coverage = documents.length ? Math.round(ready.length / documents.length * 100) : 0;
  return <div className="page overview-page"><section className="welcome-row"><div className="folio-heading"><p className="overline">Investment intelligence <i/> Folio 08—30</p><h1>Good morning, {user.name.split(" ")[0]}<em>.</em></h1><p>Your workspace is current. Here is what changed across the portfolio evidence base.</p></div><div className="welcome-action"><span>Last indexed<br/><strong>Today, 12:04 PM</strong></span><button className="button button-accent" onClick={() => navigate("studio")}><Sparkles/>Start new analysis<ArrowRight/></button></div></section>
    <section className="metric-strip"><Metric icon={LibraryBig} label="Indexed sources" value={String(ready.length)} note={`${documents.length - ready.length} awaiting review`} trend="+2 this week"/><Metric icon={BookOpen} label="Pages searchable" value={pages.toLocaleString()} note="Across the full workspace" trend="+18.4%"/><Metric icon={FileChartColumn} label="Analyses generated" value="24" note="During the last 30 days" trend="+7 this week"/><Metric icon={Target} label="Citation coverage" value="96%" note="Claims linked to evidence" trend="Strong"/></section>
    <div className="overview-grid"><section className="surface intelligence-panel"><div className="surface-head"><div><p className="overline">Portfolio signal</p><h2>Research coverage</h2></div><button className="quiet-button" onClick={() => navigate("documents")}>View data room<ArrowRight/></button></div><div className="coverage-viz"><div className="coverage-ring" style={{"--coverage": `${coverage * 3.6}deg`} as CSSProperties}><div><strong>{coverage}%</strong><span>indexed</span></div></div><div className="coverage-copy"><h3>Evidence base is ready</h3><p>{ready.length} of {documents.length} sources are indexed and available for retrieval.</p><div className="coverage-bars"><CoverageRow label="Portfolio reporting" value={92} color="navy"/><CoverageRow label="Policy & mandate" value={78} color="teal"/><CoverageRow label="Market research" value={64} color="gold"/></div></div></div></section>
      <section className="surface activity-panel"><div className="surface-head"><div><p className="overline">Source register / 05</p><h2>Latest sources</h2></div><button className="icon-quiet"><MoreHorizontal/></button></div><div className="source-mini-list">{documents.slice(0, 4).map((document, index) => <article key={document.id}><span className="source-ordinal">{String(index + 1).padStart(2,"0")}</span><div className={`document-tile file-${index % 3}`}><FileText/></div><div><strong>{document.filename}</strong><span>{document.page_count ? `${document.page_count} pages` : "Indexing"} · {relativeDate(document.created_at)}</span></div><Status status={document.status}/></article>)}</div><button className="panel-link" onClick={() => navigate("documents")}>Open source library <ArrowRight/></button></section>
    </div>
    <section className="workflow-section"><div className="section-title"><div><p className="overline">Accelerated workflows</p><h2>Move from evidence to action</h2></div><p>Structured prompts tuned for common investment research tasks.</p></div><div className="workflow-grid">{modes.slice(0,3).map((item, index) => <button key={item.id} onClick={() => navigate("studio")}><span className={`workflow-number n${index}`}>0{index + 1}</span><item.icon/><div><strong>{item.label}</strong><p>{item.short}</p></div><ArrowRight/></button>)}</div></section>
  </div>;
}

function Metric({icon: Icon, label, value, note, trend}: {icon: typeof Activity; label: string; value: string; note: string; trend: string}) { return <article><div className="metric-label"><span><Icon/></span>{label}</div><div className="metric-value"><strong>{value}</strong><b>{trend}</b></div><p>{note}</p></article>; }
function CoverageRow({label, value, color}: {label: string; value: number; color: string}) { return <div><span>{label}<b>{value}%</b></span><i><em className={color} style={{width: `${value}%`}}/></i></div>; }
function relativeDate(value: string) { const days = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 86400000)); return days === 0 ? "Today" : days === 1 ? "Yesterday" : `${days} days ago`; }

function Studio({documents, selected, setSelected, mode, setMode, query, setQuery, generate, busy, result}: {documents: Document[]; selected: string[]; setSelected: (ids: string[]) => void; mode: Mode; setMode: (m: Mode) => void; query: string; setQuery: (q: string) => void; generate: () => void; busy: boolean; result: Result | null}) {
  const ready = documents.filter(d => d.status === "ready"); const current = modes.find(item => item.id === mode)!;
  return <div className="page studio-page"><div className="page-heading editorial-heading"><div><p className="overline">Research memorandum / New</p><h1>Analysis desk<em>.</em></h1><p>Build an evidence-backed output from your private source library.</p></div><div className="heading-note"><span>Method</span><strong>Semantic retrieval</strong><small>Cosine-ranked evidence</small></div><span className="secure-context"><ShieldCheck/>Private retrieval session</span></div>
    <div className={`analysis-layout ${result ? "has-result" : ""}`}><section className="analysis-builder"><div className="builder-step"><div className="step-label"><span>1</span><div><strong>Choose a workflow</strong><small>Sets the structure and analytical lens</small></div></div><div className="mode-selector">{modes.map(({id, label, short, icon: Icon}) => <button key={id} className={mode === id ? "active" : ""} onClick={() => {setMode(id); if (!query) setQuery(modes.find(item => item.id === id)!.prompt);}}><Icon/><div><strong>{label}</strong><span>{short}</span></div><Check/></button>)}</div></div>
      <div className="builder-step"><div className="step-label"><span>2</span><div><strong>Define the objective</strong><small>Be specific about scope, audience, and constraints</small></div></div><div className="prompt-box"><textarea value={query} onChange={e => setQuery(e.target.value)} placeholder={current.prompt}/><div className="prompt-tools"><span>{query.length.toLocaleString()} / 4,000</span><button onClick={() => setQuery(current.prompt)}><Zap/>Use suggested prompt</button></div></div></div>
      <div className="builder-step"><div className="step-label"><span>3</span><div><strong>Select evidence</strong><small>Only selected material will be searched</small></div></div><div className="evidence-picker"><label className={!selected.length ? "selected" : ""}><input type="checkbox" checked={!selected.length} onChange={() => setSelected([])}/><span className="check-box"><Check/></span><div className="all-sources-icon"><LibraryBig/></div><div><strong>Entire source library</strong><small>{ready.length} indexed documents</small></div></label>{ready.map(document => <label key={document.id} className={selected.includes(document.id) ? "selected" : ""}><input type="checkbox" checked={selected.includes(document.id)} onChange={() => setSelected(selected.includes(document.id) ? selected.filter(id => id !== document.id) : [...selected, document.id])}/><span className="check-box"><Check/></span><div className="small-file"><FileText/></div><div><strong>{document.filename}</strong><small>{document.page_count || 0} pages · indexed</small></div></label>)}</div></div>
      <div className="run-bar"><div><ShieldCheck/><span><strong>Evidence-bound generation</strong><small>Responses cannot access material outside this workspace.</small></span></div><button className="button button-accent" onClick={generate} disabled={busy || !query.trim() || !ready.length}>{busy ? <><Activity className="spin"/>Synthesizing evidence</> : <>Run analysis<ArrowRight/></>}</button></div></section>{result && <ResultCard result={result}/>}</div>
  </div>;
}

function ResultCard({result}: {result: Result}) {
  const [citation, setCitation] = useState<Citation | null>(null); const [copied, setCopied] = useState(false);
  const paragraphs = result.answer.split("\n").filter(Boolean);
  return <section className="result-panel"><header><div><span className="result-status"><CircleCheck/>Complete</span><h2>Evidence-backed analysis</h2><p>Generated from {result.citations.length} retrieved passages</p></div><div><button onClick={() => {void navigator.clipboard?.writeText(result.answer); setCopied(true); window.setTimeout(() => setCopied(false), 1200);}}><Copy/>{copied ? "Copied" : "Copy"}</button><button><Download/>Export</button></div></header><div className="result-meta"><span><Sparkles/>{result.model}</span><span><Clock3/>Generated just now</span><span><ShieldCheck/>Source constrained</span></div><article className="analysis-copy">{paragraphs.map((paragraph, index) => <p key={index}>{renderCitations(paragraph, result.citations, setCitation)}</p>)}</article><div className="evidence-section"><div className="evidence-head"><div><p className="overline">Supporting evidence</p><h3>{result.citations.length} source passages</h3></div><span>Ranked by semantic relevance</span></div>{result.citations.map((item, index) => <button className="citation-row" key={item.chunk_id} onClick={() => setCitation(item)}><span className="citation-index">{String(index + 1).padStart(2,"0")}</span><div><strong>{item.filename}</strong><p>{item.excerpt}</p><span>{item.page_number ? `Page ${item.page_number}` : "Document excerpt"}</span></div><div className="relevance"><strong>{Math.round(item.relevance * 100)}%</strong><span>match</span><ChevronRight/></div></button>)}</div>{citation && <CitationDrawer citation={citation} close={() => setCitation(null)}/>}</section>;
}

function renderCitations(text: string, citations: Citation[], open: (citation: Citation) => void) { const parts = text.split(/(\[S\d+\])/g); return parts.map((part, index) => { const match = part.match(/^\[S(\d+)\]$/); if (!match) return part; const citation = citations[Number(match[1]) - 1]; return citation ? <button key={index} className="inline-citation" onClick={() => open(citation)}>{match[1]}</button> : part; }); }
function CitationDrawer({citation, close}: {citation: Citation; close: () => void}) { return <div className="drawer-layer" role="dialog" aria-modal="true" aria-label="Source evidence"><button className="drawer-scrim" onClick={close}/><aside className="citation-drawer"><header><div><p className="overline">Source evidence</p><h2>{citation.filename}</h2></div><button onClick={close} aria-label="Close evidence"><X/></button></header><div className="citation-facts"><span><FileText/>Page {citation.page_number || "—"}</span><span><Target/>{Math.round(citation.relevance * 100)}% relevance</span></div><blockquote>{citation.excerpt}</blockquote><div className="source-integrity"><ShieldCheck/><div><strong>Source integrity</strong><p>This passage was retrieved directly from the indexed document. FinSight preserves the document and page reference for verification.</p></div></div><button className="button button-dark button-wide" onClick={close}>Return to analysis</button></aside></div>; }

function Documents({documents, upload, remove}: {documents: Document[]; upload: (file?: File) => void; remove: (id: string) => void}) {
  const [search, setSearch] = useState(""); const filtered = useMemo(() => documents.filter(item => item.filename.toLowerCase().includes(search.toLowerCase())), [documents, search]); const ready = documents.filter(item => item.status === "ready").length; const pages = documents.reduce((sum, item) => sum + (item.page_count || 0), 0);
  return <div className="page documents-page"><div className="page-heading editorial-heading"><div><p className="overline">Evidence register / {String(documents.length).padStart(2,"0")}</p><h1>Source library<em>.</em></h1><p>Manage the evidence available to portfolio analysis and retrieval.</p></div><label className="button button-accent"><Upload/>Upload documents<input type="file" accept=".pdf,.txt,.md,.csv" multiple hidden onChange={e => upload(e.target.files?.[0])}/></label></div><section className="library-summary"><div><LibraryBig/><span><strong>{documents.length}</strong>Total sources</span></div><div><CircleCheck/><span><strong>{ready}</strong>Fully indexed</span></div><div><BookOpen/><span><strong>{pages}</strong>Searchable pages</span></div><div className="index-health"><span>Index health <strong>{documents.length ? Math.round(ready / documents.length * 100) : 0}%</strong></span><i><em style={{width: `${documents.length ? ready / documents.length * 100 : 0}%`}}/></i></div></section><section className="surface library-surface"><div className="library-toolbar"><div className="table-search"><Search/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search sources…"/></div><button>All file types<ChevronDown/></button><button>All statuses<ChevronDown/></button><span>{filtered.length} sources</span></div>{documents.length === 0 ? <EmptyLibrary upload={upload}/> : filtered.length === 0 ? <div className="empty-library"><Search/><h3>No matching sources</h3><p>Try a different filename or clear your search.</p><button className="quiet-button" onClick={() => setSearch("")}>Clear search</button></div> : <div className="source-table"><div className="table-head"><span>Source / Reference</span><span>Collection</span><span>Folio</span><span>Added</span><span>State</span><span/></div>{filtered.map((document, index) => <div className="table-row" key={document.id}><div className="source-name"><span className="table-ordinal">{String(index + 1).padStart(2,"0")}</span><div className={`document-tile file-${index % 3}`}><FileText/></div><span><strong>{document.filename}</strong><small>{document.content_type === "application/pdf" ? "PDF document" : document.content_type} · ref {document.id.slice(0,6)}</small></span></div><span>{document.metadata_.portfolio || "General research"}</span><span>{document.page_count ?? "—"}</span><span>{relativeDate(document.created_at)}</span><Status status={document.status}/><button className="delete-button" onClick={() => void remove(document.id)} aria-label={`Delete ${document.filename}`}><Trash2/></button></div>)}</div>}</section><div className="library-footnote"><LockKeyhole/><span>Sources are encrypted in transit and isolated to this workspace. Deleting a source also removes its retrieval index.</span></div></div>;
}
function EmptyLibrary({upload}: {upload: (file?: File) => void}) { return <div className="empty-library"><div className="empty-illustration"><FileText/><span><Plus/></span></div><h3>Build your evidence base</h3><p>Add portfolio reports, investment policies, market research, or exposure data. FinSight will extract, index, and prepare every source for retrieval.</p><label className="button button-dark"><Upload/>Choose your first document<input type="file" accept=".pdf,.txt,.md,.csv" hidden onChange={e => upload(e.target.files?.[0])}/></label><span>PDF, TXT, Markdown, or CSV · Maximum 20 MB</span></div>; }
function Status({status}: {status: Document["status"]}) { return <span className={`status-pill ${status}`}>{status === "ready" ? <CircleCheck/> : status === "processing" ? <Activity className="spin"/> : <CircleAlert/>}{status === "ready" ? "Indexed" : status === "processing" ? "Processing" : "Failed"}</span>; }

function Audit({events}: {events: AuditEvent[]}) {
  return <div className="page audit-page"><div className="page-heading editorial-heading"><div><p className="overline">Control ledger / Immutable</p><h1>Audit activity<em>.</em></h1><p>A traceable history of data access and intelligence generated in this workspace.</p></div><button className="button button-secondary"><Download/>Export log</button></div><section className="audit-assurance"><div><ShieldCheck/><span><strong>Audit controls active</strong><small>All material workspace actions are recorded with actor, time, and resource identifiers.</small></span></div><span><i/>Recording normally</span></section><section className="surface audit-surface"><div className="audit-toolbar"><div className="table-search"><Search/><input placeholder="Search activity…"/></div><button>All activity<ChevronDown/></button><button>Last 30 days<ChevronDown/></button></div>{events.length ? <div className="audit-list"><div className="audit-date">Recent activity</div>{events.map((event,index) => <article key={event.id}><span className="audit-ordinal">{String(index+1).padStart(2,"0")}</span><div className={`event-icon ${event.action.split(".")[0]}`}>{event.action.startsWith("document") ? <FileText/> : event.action.startsWith("generation") ? <Sparkles/> : <Fingerprint/>}</div><div className="event-copy"><strong>{event.action === "generation.created" ? "Analysis generated" : event.action === "document.uploaded" ? "Source uploaded" : event.action === "document.deleted" ? "Source deleted" : "Workspace sign-in"}</strong><p>{event.action === "generation.created" ? `${String(event.detail.mode || "Analysis").replaceAll("_", " ")} using ${event.detail.source_count || 0} sources` : event.action === "document.uploaded" ? String(event.detail.filename || "Document added to source library") : `${event.resource_type} · ${event.resource_id?.slice(0, 8) || "system"}`}</p></div><span className="actor-chip"><span>JA</span>{previewUser.name}</span><time>{new Date(event.created_at).toLocaleString([], {month: "short", day: "numeric", hour: "numeric", minute: "2-digit"})}</time><ChevronRight/></article>)}</div> : <div className="empty-library"><ShieldCheck/><h3>No recorded activity</h3><p>Uploads, analyses, and account events will appear here.</p></div>}</section><p className="audit-note"><LockKeyhole/>Audit records are append-only and retained for governance review.</p></div>;
}
