import {FormEvent, useEffect, useState} from "react";
import {Activity, BookOpen, ChevronRight, FileText, LogOut, Menu, MessageSquareText, PieChart, Search, ShieldCheck, Sparkles, Trash2, Upload, X} from "lucide-react";
import {api, AuditEvent, Citation, Document, Result, session, User} from "./api";

const modes = [
  {id: "portfolio_summary", label: "Portfolio summary", icon: PieChart, hint: "Positioning, performance and allocation"},
  {id: "risk_insight", label: "Risk insights", icon: ShieldCheck, hint: "Material exposures and vulnerabilities"},
  {id: "client_communication", label: "Client brief", icon: MessageSquareText, hint: "Clear, client-ready communication"},
  {id: "question", label: "Ask sources", icon: Search, hint: "Explore the indexed knowledge base"}
];

function Auth({onReady}: {onReady: (user: User) => void}) {
  const [registering, setRegistering] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const data = new FormData(event.currentTarget); try { if (registering) await api.register(String(data.get("name")), String(data.get("email")), String(data.get("password"))); await api.login(String(data.get("email")), String(data.get("password"))); onReady(await api.me()); } catch (e) { setError(e instanceof Error ? e.message : "Unable to continue"); } finally { setBusy(false); } }
  return <main className="auth-shell"><section className="auth-story"><div className="brand"><span className="brand-mark"><Activity /></span>FinSight</div><div className="story-copy"><p className="eyebrow">Grounded financial intelligence</p><h1>Decisions begin with evidence.</h1><p>Turn fragmented financial documents into auditable portfolio intelligence—with every insight traced to its source.</p><div className="trust-row"><span><ShieldCheck /> Secure by design</span><span><BookOpen /> Source grounded</span></div></div><p className="legal">Built for analysts and advisors who value clarity.</p></section><section className="auth-panel"><form className="auth-card" onSubmit={submit}><div><p className="eyebrow">{registering ? "Create your workspace" : "Welcome back"}</p><h2>{registering ? "Start exploring" : "Sign in to FinSight"}</h2></div>{registering && <label>Full name<input name="name" required minLength={2} autoComplete="name" placeholder="Alex Morgan" /></label>}<label>Work email<input name="email" type="email" required autoComplete="email" placeholder="alex@firm.com" /></label><label>Password<input name="password" type="password" required minLength={12} autoComplete={registering ? "new-password" : "current-password"} placeholder="12 or more characters" /></label>{error && <p className="error">{error}</p>}<button className="primary" disabled={busy}>{busy ? "Please wait…" : registering ? "Create account" : "Sign in"}<ChevronRight /></button><button className="text-button" type="button" onClick={() => {setRegistering(!registering); setError("");}}>{registering ? "Already have an account? Sign in" : "New to FinSight? Create an account"}</button><p className="security-note"><ShieldCheck /> Protected with encrypted credentials and short-lived sessions.</p></form></section></main>;
}

function App() {
  const [user, setUser] = useState<User | null>(null); const [loading, setLoading] = useState(Boolean(session.token));
  useEffect(() => { if (session.token) api.me().then(setUser).catch(() => session.clear()).finally(() => setLoading(false)); }, []);
  if (loading) return <div className="loading"><Activity className="spin" />Loading workspace</div>;
  if (!user) return <Auth onReady={setUser} />;
  return <Workspace user={user} onLogout={() => {session.clear(); setUser(null);}} />;
}

function Workspace({user, onLogout}: {user: User; onLogout: () => void}) {
  const [documents, setDocuments] = useState<Document[]>([]); const [selected, setSelected] = useState<string[]>([]); const [mode, setMode] = useState("portfolio_summary"); const [query, setQuery] = useState(""); const [result, setResult] = useState<Result | null>(null); const [audit, setAudit] = useState<AuditEvent[]>([]); const [tab, setTab] = useState<"studio" | "documents" | "audit">("studio"); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [mobile, setMobile] = useState(false);
  const load = () => api.documents().then(setDocuments).catch(e => setError(e.message));
  useEffect(load, []); useEffect(() => { const pending = documents.some(d => d.status === "processing"); if (!pending) return; const timer = window.setInterval(load, 2500); return () => clearInterval(timer); }, [documents]);
  async function upload(file?: File) { if (!file) return; setBusy(true); setError(""); try { await api.upload(file, ""); await load(); setTab("documents"); } catch (e) { setError(e instanceof Error ? e.message : "Upload failed"); } finally {setBusy(false);} }
  async function generate() { if (!query.trim()) return; setBusy(true); setError(""); try { setResult(await api.generate(query, mode, selected)); } catch (e) {setError(e instanceof Error ? e.message : "Generation failed");} finally {setBusy(false);} }
  async function openAudit() { setTab("audit"); setAudit(await api.audit()); }
  const nav = (next: typeof tab) => {setTab(next); setMobile(false);};
  return <div className="workspace"><aside className={mobile ? "sidebar open" : "sidebar"}><div className="brand"><span className="brand-mark"><Activity /></span>FinSight<button className="close-nav" onClick={() => setMobile(false)}><X /></button></div><nav><button className={tab === "studio" ? "active" : ""} onClick={() => nav("studio")}><Sparkles />Intelligence studio</button><button className={tab === "documents" ? "active" : ""} onClick={() => nav("documents")}><FileText />Source library<span className="count">{documents.length}</span></button><button className={tab === "audit" ? "active" : ""} onClick={openAudit}><ShieldCheck />Audit trail</button></nav><div className="sidebar-foot"><div className="avatar">{user.name.split(" ").map(n => n[0]).slice(0,2)}</div><div><strong>{user.name}</strong><small>{user.role}</small></div><button aria-label="Sign out" onClick={onLogout}><LogOut /></button></div></aside><div className="main"><header><button className="menu" onClick={() => setMobile(true)}><Menu /></button><div><p className="eyebrow">Private workspace</p><h2>{tab === "studio" ? "Intelligence studio" : tab === "documents" ? "Source library" : "Audit trail"}</h2></div><label className="upload-button"><Upload />{busy ? "Working…" : "Add sources"}<input type="file" accept=".pdf,.txt,.md,.csv" hidden disabled={busy} onChange={e => upload(e.target.files?.[0])} /></label></header>{error && <div className="alert"><span>{error}</span><button onClick={() => setError("")}><X /></button></div>}{tab === "studio" && <Studio documents={documents} selected={selected} setSelected={setSelected} mode={mode} setMode={setMode} query={query} setQuery={setQuery} generate={generate} busy={busy} result={result} />}{tab === "documents" && <Documents documents={documents} upload={upload} remove={async id => {await api.removeDocument(id); setDocuments(d => d.filter(x => x.id !== id));}} />}{tab === "audit" && <Audit events={audit} />}</div></div>;
}

function Studio({documents, selected, setSelected, mode, setMode, query, setQuery, generate, busy, result}: {documents: Document[]; selected: string[]; setSelected: (ids: string[]) => void; mode: string; setMode: (m: string) => void; query: string; setQuery: (q: string) => void; generate: () => void; busy: boolean; result: Result | null}) {
  const ready = documents.filter(d => d.status === "ready"); return <div className="studio"><section><div className="section-head"><div><p className="eyebrow">Choose a workflow</p><h3>What would you like to create?</h3></div></div><div className="mode-grid">{modes.map(({id,label,icon:Icon,hint}) => <button className={mode === id ? "mode active" : "mode"} onClick={() => setMode(id)} key={id}><Icon /><strong>{label}</strong><small>{hint}</small></button>)}</div><div className="composer"><div className="source-picker"><span>Ground with</span><button onClick={() => setSelected([])} className={!selected.length ? "active" : ""}>All sources</button>{ready.slice(0,3).map(d => <button key={d.id} className={selected.includes(d.id) ? "active" : ""} onClick={() => setSelected(selected.includes(d.id) ? selected.filter(id => id !== d.id) : [...selected, d.id])}>{d.filename}</button>)}</div><textarea value={query} onChange={e => setQuery(e.target.value)} placeholder={mode === "risk_insight" ? "Identify the most material portfolio risks and explain the supporting evidence…" : "Describe the insight or communication you need…"} /><div className="composer-foot"><span>{ready.length} indexed {ready.length === 1 ? "source" : "sources"}</span><button className="primary" onClick={generate} disabled={busy || !query.trim() || !ready.length}><Sparkles />{busy ? "Analyzing…" : "Generate insight"}</button></div></div></section>{result && <ResultCard result={result} />}</div>;
}

function ResultCard({result}: {result: Result}) { const [citation, setCitation] = useState<Citation | null>(null); return <section className="result"><div className="section-head"><div><p className="eyebrow">Source-grounded output</p><h3>Analysis</h3></div><span className="model">{result.model}</span></div><div className="answer">{result.answer.split("\n").map((p,i) => <p key={i}>{p}</p>)}</div><div className="citations"><strong>Evidence · {result.citations.length} sources</strong>{result.citations.map((c,i) => <button key={c.chunk_id} onClick={() => setCitation(c)}><span>{i+1}</span><div><strong>{c.filename}</strong><small>{c.page_number ? `Page ${c.page_number} · ` : ""}{Math.round(c.relevance*100)}% match</small></div><ChevronRight /></button>)}</div>{citation && <div className="citation-modal" onClick={() => setCitation(null)}><article onClick={e => e.stopPropagation()}><button className="modal-close" onClick={() => setCitation(null)}><X /></button><p className="eyebrow">Evidence excerpt</p><h3>{citation.filename}</h3><p>{citation.excerpt}</p><small>{citation.page_number ? `Page ${citation.page_number}` : "Document excerpt"} · {Math.round(citation.relevance*100)}% relevance</small></article></div>}</section> }

function Documents({documents, upload, remove}: {documents: Document[]; upload: (file?: File) => void; remove: (id:string) => void}) { return <section className="library"><label className="dropzone"><Upload /><strong>Add financial documents</strong><span>PDF, TXT, Markdown or CSV · up to 20 MB</span><input type="file" accept=".pdf,.txt,.md,.csv" hidden onChange={e => upload(e.target.files?.[0])} /></label><div className="document-list">{documents.map(d => <article key={d.id}><span className="file-icon"><FileText /></span><div><strong>{d.filename}</strong><small>{d.page_count ? `${d.page_count} pages · ` : ""}{new Date(d.created_at).toLocaleDateString()}</small></div><span className={`status ${d.status}`}>{d.status}</span><button aria-label={`Delete ${d.filename}`} onClick={() => remove(d.id)}><Trash2 /></button></article>)}{!documents.length && <p className="empty">Your source library is empty. Add a document to begin.</p>}</div></section> }
function Audit({events}: {events: AuditEvent[]}) { return <section className="audit"><div className="callout"><ShieldCheck /><div><strong>Immutable activity history</strong><p>Every upload, generation, and account event is recorded for review.</p></div></div>{events.map(e => <article key={e.id}><span className="event-dot"/><div><strong>{e.action.replaceAll(".", " ")}</strong><small>{e.resource_type}{e.resource_id ? ` · ${e.resource_id.slice(0,8)}` : ""}</small></div><time>{new Date(e.created_at).toLocaleString()}</time></article>)}</section> }

export default App;
